apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iceberg-roles
  resourceVersion: '3324928'
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
