catalog:
  db:
    host: 'localhost'
    name: 'icebergdb'
    user: 'iceberg'
    password: ''


  s3:
    bucket: 'maarten-dev'
    warehouse_dir: 'warehouse'
    endpoint: 'https://localhost:9000'
    access_key: ''
    secret_key: ''
  security:
    token: 'secret-123'
  
server:
 port: 8182

spring:
 application: 
   name: 'iceberg-catalog-server-service'
 cloud:
    bootstrap:
      enabled: true
    kubernetes:
      config:
        enabled: true
      enabled: true
      reload:
        enabled: true
 
