catalog:
  db:
    host: 'labs-db1.sidnlabs.nl'
    name: 'icebergdb'
    user: 'iceberg'
    password: 'fOez0eC6TxgaCufnIEPS'


  s3:
    bucket: 'maarten-dev'
    warehouse_dir: 'warehouse'
    endpoint: 'https://s3-lb.sidnlabs.nl:9000'
    access_key: 'FnrCQc3JQXEM1OwAtrSg'
    secret_key: 'dNITppQxnZbjIHs1AOejZuPDnNOG5emYHhbj5ar2'
  security:
    token: 'secret-123'
  
server:
 port: 8182

spring:
 application: 
   name: 'iceberg-catalog-server-service'
 cloud:
    bootstrap:
      enabled: true
    kubernetes:
      config:
        enabled: true
      enabled: true
      reload:
        enabled: true
 
