server:
  port: 8182
 
catalog:
  db:
    url: '${ICEBERG_CATALOG_DB_URL}'
    name: 'iceberg'
    user: '${ICEBERG_CATALOG_DB_USER}'
    password: '${ICEBERG_CATALOG_DB_PASSWORD}'

  s3:
    bucket: 'sidnlabs-iceberg-data'
    warehouse_dir: 'warehouse'
    endpoint:
    access-key: '${AWS_ACCESS_KEY_ID}'
    secret-key: '${AWS_SECRET_ACCESS_KEY}'
  security:
    token: 'secret_token_change_me_fast'
      
  
spring:
 application: 
   name: 'iceberg-catalog-server'
 cloud:
    bootstrap:
      enabled: false
    kubernetes:
      config:
        enabled: false
    enabled: false